/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Table = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'seats' : IDL.Nat,
});
export const BillItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const Bill = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Float64,
  'settled' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tableId' : IDL.Text,
  'orderId' : IDL.Text,
  'billNumber' : IDL.Nat,
  'discount' : IDL.Float64,
  'tableName' : IDL.Text,
  'items' : IDL.Vec(BillItem),
  'taxAmount' : IDL.Float64,
  'subtotal' : IDL.Float64,
  'settlementMode' : IDL.Text,
  'cashierName' : IDL.Text,
  'restaurantId' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'note' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'menuItemId' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'tableId' : IDL.Text,
  'specialInstructions' : IDL.Text,
  'tableName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const RestaurantSettings = IDL.Record({
  'name' : IDL.Text,
  'footerMessage' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'taxRate' : IDL.Float64,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'visitCount' : IDL.Nat,
  'createdAt' : IDL.Int,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'quantity' : IDL.Float64,
  'unit' : IDL.Text,
  'reorderLevel' : IDL.Float64,
  'costPrice' : IDL.Float64,
  'updatedAt' : IDL.Int,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'category' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
  'date' : IDL.Int,
  'paidBy' : IDL.Text,
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'phone' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'balanceDue' : IDL.Float64,
  'createdAt' : IDL.Int,
});
export const PurchaseItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Float64,
  'unit' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const Purchase = IDL.Record({
  'id' : IDL.Text,
  'vendorId' : IDL.Text,
  'vendorName' : IDL.Text,
  'items' : IDL.Vec(PurchaseItem),
  'totalAmount' : IDL.Float64,
  'date' : IDL.Int,
  'paymentStatus' : IDL.Text,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [MenuItem],
      [],
    ),
  'addTable' : IDL.Func([IDL.Text, IDL.Nat], [Table], []),
  'createBill' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(BillItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Bill],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Text],
      [Order],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTable' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBill' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getBillsByRestaurant' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
  'clearRestaurantBills' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderByTable' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getSettings' : IDL.Func([], [RestaurantSettings], ['query']),
  'getTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
  'markBillSettled' : IDL.Func([IDL.Text], [IDL.Opt(Bill)], []),
  'resettleBill' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Bill)], []),
  'updateBill' : IDL.Func([Bill], [IDL.Opt(Bill)], []),
  'getDueBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'updateMenuItem' : IDL.Func([MenuItem], [IDL.Opt(MenuItem)], []),
  'updateOrderItems' : IDL.Func(
      [IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Opt(Order)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], []),
  'updateSettings' : IDL.Func([RestaurantSettings], [], []),
  'updateTableStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Table)], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Customer], []),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'updateCustomer' : IDL.Func([Customer], [IDL.Opt(Customer)], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addInventoryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64, IDL.Float64], [InventoryItem], []),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'updateInventoryItem' : IDL.Func([InventoryItem], [IDL.Opt(InventoryItem)], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addExpense' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [Expense], []),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Vendor], []),
  'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'updateVendor' : IDL.Func([Vendor], [IDL.Opt(Vendor)], []),
  'deleteVendor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addPurchase' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(PurchaseItem), IDL.Float64, IDL.Text, IDL.Text], [Purchase], []),
  'getPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'updatePurchaseStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Purchase)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Table = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'seats' : IDL.Nat,
  });
  const BillItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const Bill = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Float64,
    'settled' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tableId' : IDL.Text,
    'orderId' : IDL.Text,
    'billNumber' : IDL.Nat,
    'discount' : IDL.Float64,
    'tableName' : IDL.Text,
    'items' : IDL.Vec(BillItem),
    'taxAmount' : IDL.Float64,
    'subtotal' : IDL.Float64,
    'settlementMode' : IDL.Text,
    'cashierName' : IDL.Text,
    'restaurantId' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'note' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'menuItemId' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'tableId' : IDL.Text,
    'specialInstructions' : IDL.Text,
    'tableName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const RestaurantSettings = IDL.Record({
    'name' : IDL.Text,
    'footerMessage' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'taxRate' : IDL.Float64,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'visitCount' : IDL.Nat,
    'createdAt' : IDL.Int,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'quantity' : IDL.Float64,
    'unit' : IDL.Text,
    'reorderLevel' : IDL.Float64,
    'costPrice' : IDL.Float64,
    'updatedAt' : IDL.Int,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'category' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
    'date' : IDL.Int,
    'paidBy' : IDL.Text,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'phone' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'balanceDue' : IDL.Float64,
    'createdAt' : IDL.Int,
  });
  const PurchaseItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Float64,
    'unit' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const Purchase = IDL.Record({
    'id' : IDL.Text,
    'vendorId' : IDL.Text,
    'vendorName' : IDL.Text,
    'items' : IDL.Vec(PurchaseItem),
    'totalAmount' : IDL.Float64,
    'date' : IDL.Int,
    'paymentStatus' : IDL.Text,
    'notes' : IDL.Text,
  });

  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [MenuItem],
        [],
      ),
    'addTable' : IDL.Func([IDL.Text, IDL.Nat], [Table], []),
    'createBill' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(BillItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Bill],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Text],
        [Order],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTable' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBill' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getBillsByRestaurant' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
    'clearRestaurantBills' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderByTable' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getSettings' : IDL.Func([], [RestaurantSettings], ['query']),
    'getTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
    'markBillSettled' : IDL.Func([IDL.Text], [IDL.Opt(Bill)], []),
    'resettleBill' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Bill)], []),
    'updateBill' : IDL.Func([Bill], [IDL.Opt(Bill)], []),
    'getDueBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'updateMenuItem' : IDL.Func([MenuItem], [IDL.Opt(MenuItem)], []),
    'updateOrderItems' : IDL.Func(
        [IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Opt(Order)],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], []),
    'updateSettings' : IDL.Func([RestaurantSettings], [], []),
    'updateTableStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Table)], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Customer], []),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'updateCustomer' : IDL.Func([Customer], [IDL.Opt(Customer)], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addInventoryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64, IDL.Float64], [InventoryItem], []),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'updateInventoryItem' : IDL.Func([InventoryItem], [IDL.Opt(InventoryItem)], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addExpense' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [Expense], []),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Vendor], []),
    'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'updateVendor' : IDL.Func([Vendor], [IDL.Opt(Vendor)], []),
    'deleteVendor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addPurchase' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(PurchaseItem), IDL.Float64, IDL.Text, IDL.Text], [Purchase], []),
    'getPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'updatePurchaseStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Purchase)], []),
  });
};

export const init = ({ IDL }) => { return []; };
