/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : string,
  'total' : number,
  'settled' : boolean,
  'createdAt' : bigint,
  'tableId' : string,
  'orderId' : string,
  'billNumber' : bigint,
  'discount' : number,
  'tableName' : string,
  'items' : Array<BillItem>,
  'taxAmount' : number,
  'subtotal' : number,
  'settlementMode' : string,
  'cashierName' : string,
  'restaurantId' : string,
}
export interface BillItem {
  'name' : string,
  'quantity' : bigint,
  'price' : number,
  'subtotal' : number,
}
export interface MenuItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'tableId' : string,
  'specialInstructions' : string,
  'tableName' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'note' : string,
  'quantity' : bigint,
  'price' : number,
  'menuItemId' : string,
}
export interface RestaurantSettings {
  'name' : string,
  'footerMessage' : string,
  'currency' : string,
  'address' : string,
  'phone' : string,
  'taxRate' : number,
}
export interface Table {
  'id' : string,
  'status' : string,
  'name' : string,
  'seats' : bigint,
}
export interface Customer {
  'id' : string,
  'name' : string,
  'phone' : string,
  'email' : string,
  'address' : string,
  'loyaltyPoints' : bigint,
  'visitCount' : bigint,
  'createdAt' : bigint,
}
export interface InventoryItem {
  'id' : string,
  'name' : string,
  'category' : string,
  'quantity' : number,
  'unit' : string,
  'reorderLevel' : number,
  'costPrice' : number,
  'updatedAt' : bigint,
}
export interface Expense {
  'id' : string,
  'category' : string,
  'description' : string,
  'amount' : number,
  'date' : bigint,
  'paidBy' : string,
}
export interface Vendor {
  'id' : string,
  'name' : string,
  'contactPerson' : string,
  'phone' : string,
  'email' : string,
  'address' : string,
  'category' : string,
  'balanceDue' : number,
  'createdAt' : bigint,
}
export interface PurchaseItem {
  'name' : string,
  'quantity' : number,
  'unit' : string,
  'unitPrice' : number,
  'subtotal' : number,
}
export interface Purchase {
  'id' : string,
  'vendorId' : string,
  'vendorName' : string,
  'items' : Array<PurchaseItem>,
  'totalAmount' : number,
  'date' : bigint,
  'paymentStatus' : string,
  'notes' : string,
}
export interface _SERVICE {
  // Legacy (global) functions
  'addMenuItem' : ActorMethod<[string, string, number, string], MenuItem>,
  'addTable' : ActorMethod<[string, bigint], Table>,
  'createBill' : ActorMethod<
    [string, string, string, Array<BillItem>, number, number, number, number, string, string, string],
    Bill
  >,
  'createOrder' : ActorMethod<[string, string, Array<OrderItem>, string], Order>,
  'deleteMenuItem' : ActorMethod<[string], boolean>,
  'deleteTable' : ActorMethod<[string], boolean>,
  'deleteBill' : ActorMethod<[string], boolean>,
  'getBills' : ActorMethod<[], Array<Bill>>,
  'getBillsByRestaurant' : ActorMethod<[string], Array<Bill>>,
  'clearRestaurantBills' : ActorMethod<[string], bigint>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrderByTable' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getSettings' : ActorMethod<[], RestaurantSettings>,
  'getTables' : ActorMethod<[], Array<Table>>,
  'markBillSettled' : ActorMethod<[string], [] | [Bill]>,
  'resettleBill' : ActorMethod<[string, string], [] | [Bill]>,
  'updateBill' : ActorMethod<[Bill], [] | [Bill]>,
  'getDueBills' : ActorMethod<[], Array<Bill>>,
  'updateMenuItem' : ActorMethod<[MenuItem], [] | [MenuItem]>,
  'updateOrderItems' : ActorMethod<[string, Array<OrderItem>], [] | [Order]>,
  'updateOrderStatus' : ActorMethod<[string, string], [] | [Order]>,
  'updateSettings' : ActorMethod<[RestaurantSettings], undefined>,
  'updateTableStatus' : ActorMethod<[string, string], [] | [Table]>,
  'addCustomer' : ActorMethod<[string, string, string, string], Customer>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'updateCustomer' : ActorMethod<[Customer], [] | [Customer]>,
  'deleteCustomer' : ActorMethod<[string], boolean>,
  'addInventoryItem' : ActorMethod<[string, string, number, string, number, number], InventoryItem>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], [] | [InventoryItem]>,
  'deleteInventoryItem' : ActorMethod<[string], boolean>,
  'addExpense' : ActorMethod<[string, string, number, string], Expense>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'deleteExpense' : ActorMethod<[string], boolean>,
  'addVendor' : ActorMethod<[string, string, string, string, string, string], Vendor>,
  'getVendors' : ActorMethod<[], Array<Vendor>>,
  'updateVendor' : ActorMethod<[Vendor], [] | [Vendor]>,
  'deleteVendor' : ActorMethod<[string], boolean>,
  'addPurchase' : ActorMethod<[string, string, Array<PurchaseItem>, number, string, string], Purchase>,
  'getPurchases' : ActorMethod<[], Array<Purchase>>,
  'updatePurchaseStatus' : ActorMethod<[string, string], [] | [Purchase]>,
  'deletePurchase' : ActorMethod<[string], boolean>,
  // Restaurant-scoped (R) functions — full per-restaurant isolation
  'getTablesR' : ActorMethod<[string], Array<Table>>,
  'addTableR' : ActorMethod<[string, string, bigint], Table>,
  'deleteTableR' : ActorMethod<[string, string], boolean>,
  'getMenuItemsR' : ActorMethod<[string], Array<MenuItem>>,
  'addMenuItemR' : ActorMethod<[string, string, string, number, string], MenuItem>,
  'updateMenuItemR' : ActorMethod<[string, MenuItem], [] | [MenuItem]>,
  'deleteMenuItemR' : ActorMethod<[string, string], boolean>,
  'getOrdersR' : ActorMethod<[string], Array<Order>>,
  'getOrderByTableR' : ActorMethod<[string, string], [] | [Order]>,
  'createOrderR' : ActorMethod<[string, string, string, Array<OrderItem>, string], Order>,
  'updateOrderItemsR' : ActorMethod<[string, string, Array<OrderItem>], [] | [Order]>,
  'updateOrderStatusR' : ActorMethod<[string, string, string], [] | [Order]>,
  'getSettingsR' : ActorMethod<[string], RestaurantSettings>,
  'updateSettingsR' : ActorMethod<[string, RestaurantSettings], undefined>,
  'clearRestaurantBillsAndReset' : ActorMethod<[string], bigint>,
  'createBillR' : ActorMethod<
    [string, string, string, string, Array<BillItem>, number, number, number, number, string, string],
    Bill
  >,
  'resetBillCounter' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
