/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillItem {
    name: string;
    quantity: bigint;
    price: number;
    subtotal: number;
}
export interface MenuItem {
    id: string;
    name: string;
    description: string;
    available: boolean;
    category: string;
    price: number;
}
export interface Table {
    id: string;
    status: string;
    name: string;
    seats: bigint;
}
export interface RestaurantSettings {
    name: string;
    footerMessage: string;
    currency: string;
    address: string;
    phone: string;
    taxRate: number;
}
export interface Bill {
    id: string;
    total: number;
    settled: boolean;
    createdAt: bigint;
    tableId: string;
    orderId: string;
    billNumber: bigint;
    discount: number;
    tableName: string;
    items: Array<BillItem>;
    taxAmount: number;
    subtotal: number;
    settlementMode: string;
    cashierName: string;
    restaurantId: string;
}
export interface OrderItem {
    name: string;
    note: string;
    quantity: bigint;
    price: number;
    menuItemId: string;
}
export interface Order {
    id: string;
    status: string;
    createdAt: bigint;
    tableId: string;
    specialInstructions: string;
    tableName: string;
    items: Array<OrderItem>;
}
export interface backendInterface {
    addMenuItem(category: string, itemName: string, itemPrice: number, itemDescription: string): Promise<MenuItem>;
    addTable(tableName: string, seatsCount: bigint): Promise<Table>;
    createBill(orderId: string, tableId: string, tableName: string, billItems: Array<BillItem>, subtotal: number, taxAmount: number, discount: number, total: number, settlementMode: string, cashierName: string, restaurantId: string): Promise<Bill>;
    resettleBill(billId: string, newMode: string): Promise<Bill | null>;
    markBillSettled(billId: string): Promise<Bill | null>;
    updateBill(bill: Bill): Promise<Bill | null>;
    deleteBill(billId: string): Promise<boolean>;
    getBills(): Promise<Array<Bill>>;
    getBillsByRestaurant(restaurantId: string): Promise<Array<Bill>>;
    clearRestaurantBills(restaurantId: string): Promise<bigint>;
    getDueBills(): Promise<Array<Bill>>;
    createOrder(tableId: string, tableName: string, orderItems: Array<OrderItem>, instructions: string): Promise<Order>;
    deleteMenuItem(itemId: string): Promise<boolean>;
    deleteTable(tableId: string): Promise<boolean>;
    getMenuItems(): Promise<Array<MenuItem>>;
    getOrderByTable(tableId: string): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getSettings(): Promise<RestaurantSettings>;
    getTables(): Promise<Array<Table>>;
    updateMenuItem(item: MenuItem): Promise<MenuItem | null>;
    updateOrderItems(orderId: string, items: Array<OrderItem>): Promise<Order | null>;
    updateOrderStatus(orderId: string, newStatus: string): Promise<Order | null>;
    updateSettings(newSettings: RestaurantSettings): Promise<void>;
    updateTableStatus(tableId: string, newStatus: string): Promise<Table | null>;
}
import type { MenuItem as _MenuItem, Order as _Order, Table as _Table, Bill as _Bill } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMenuItem(arg0: string, arg1: string, arg2: number, arg3: string): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTable(arg0: string, arg1: bigint): Promise<Table> {
        if (this.processError) {
            try {
                const result = await this.actor.addTable(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTable(arg0, arg1);
            return result;
        }
    }
    async createBill(arg0: string, arg1: string, arg2: string, arg3: Array<BillItem>, arg4: number, arg5: number, arg6: number, arg7: number, arg8: string, arg9: string, arg10: string): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async resettleBill(arg0: string, arg1: string): Promise<Bill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.resettleBill(arg0, arg1);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resettleBill(arg0, arg1);
            return result.length === 0 ? null : result[0];
        }
    }
    async markBillSettled(arg0: string): Promise<Bill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markBillSettled(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBillSettled(arg0);
            return result.length === 0 ? null : result[0];
        }
    }
    async updateBill(arg0: Bill): Promise<Bill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(arg0);
            return result.length === 0 ? null : result[0];
        }
    }
    async deleteBill(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async getBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBills();
            return result;
        }
    }
    async getBillsByRestaurant(arg0: string): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillsByRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillsByRestaurant(arg0);
            return result;
        }
    }
    async clearRestaurantBills(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.clearRestaurantBills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearRestaurantBills(arg0);
            return result;
        }
    }
    async getDueBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueBills();
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: Array<OrderItem>, arg3: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteMenuItem(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteTable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTable(arg0);
            return result;
        }
    }
    async getMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems();
            return result;
        }
    }
    async getOrderByTable(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderByTable(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderByTable(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return result;
        }
    }
    async getSettings(): Promise<RestaurantSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTables(): Promise<Array<Table>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTables();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTables();
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItem): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderItems(arg0: string, arg1: Array<OrderItem>): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderItems(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderItems(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: string, arg1: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: RestaurantSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateTableStatus(arg0: string, arg1: string): Promise<Table | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTableStatus(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTableStatus(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Table]): Table | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
